fix: static imports
This should fix the error blocking the upgrade to vue-tsc v0.31.1

```
tests/components/ScriptSetupWithChildren.vue:10:1 - error TS1232: An import declaration can only be used in a namespace or module.

10 import ScriptSetup from './ScriptSetup.vue'
   ~~~~~~

tests/components/ScriptSetupWithChildren.vue:11:1 - error TS1232: An import declaration can only be used in a namespace or module.

11 import WithProps from './WithProps.vue'
   ~~~~~~
```